# Generated by Django 5.0.4 on 2024-04-08 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000000000000)),
                ('date', models.IntegerField(blank=True, default=datetime.datetime(2024, 4, 8, 20, 16, 48, 185959))),
                ('user', models.CharField(max_length=100000)),
                ('room', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100000000)),
            ],
        ),
    ]
